common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'common'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="common/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),

    # account settings
    path("settings/base/", views.base, name="settings_base"),
    # path("settings/password_change/", settings_views.PasswordChangeView.as_view(), name="password_change),
    path("settings/image/", views.profile_modify_image, name="settings_image"),
    # path("settings/image/delete/", settings_views.profile_image_delete, name="settings_image_delete"),
    path('settings/password_reset/', views.password_reset, name='password_reset'),

    # account page
    path("account_page/", views.account_page, name="account_page"),

    # ranking page
    path('ranking/', views.ranking, name='ranking'),

    # point policy page
    path("point_policy/", views.point_policy, name="point_policy"),

    # attendance page
    path('attendance/', views.attendance, name='attendance'),

    path('transactions/<int:transaction_id>/', views.transaction_detail, name='transaction_detail'),

    path('referral/', views.referral_view, name='referral'),

    path('user/<int:user_id>/questions/', views.user_questions, name='user_questions'),

    path('user/<int:user_id>/answers/', views.user_answers, name='user_answers'),

    path('user/<int:user_id>/comments/', views.user_comments, name='user_comments'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings
from django.conf.urls.static import static
from pybo.views import indicator_views, ai_indicator_views, profile_click_views, independent_indicator_views, nlp_dashboard_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
    # crypto fear greed index GPT response
    path('fetch_ai_analysis/',
         indicator_views.fetch_ai_analysis, name='fetch_ai_analysis'),
    path('fetch_ai_analysis_global/',
         indicator_views.fetch_ai_analysis_global, name='fetch_ai_analysis_global'),
    path('fetch_ai_technical/',
         indicator_views.fetch_ai_technical, name='fetch_ai_technical'),
    path('fetch_ai_corr/',
         ai_indicator_views.fetch_ai_corr, name='fetch_ai_corr'),
    path('fetch_forecast/',
         ai_indicator_views.time_series_views, name='fetch_forecast'),
    path('search_news/',
         ai_indicator_views.search_news, name='search_news'),
    path('fetch-time-series-analysis-indicator-page/<str:timeframe>/',
         independent_indicator_views.time_series_analysis, name='time_series_analysis'),
    path('fetch-gpt-analysis/<str:timeframe>/',
         independent_indicator_views.fetch_ai_analysis, name='fetch_ai_analysis'),
    path('news_similarity/',
         nlp_dashboard_views.search_news, name="nlp_dashboard_search_news"),
    path('search_chart_pattern/',
         nlp_dashboard_views.search_chart_pattern, name="nlp_dashboard_search_chart_patterns"),
]

handler404 = 'common.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views, free_board_views, indicator_views, profile_click_views, component_views, ai_indicator_views, trading_bot_views, independent_indicator_views, nlp_dashboard_views
app_name = "pybo"

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name="index"),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    #path('question/create/',
    #     question_views.question_create, name='question_create'),
    path('question/create/<str:board_name>/',
         question_views.question_create, name="question_create"),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/questions/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/',
         vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/',
         vote_views.vote_answer, name='vote_answer'),

    # independent indicators
    path('independent_indicators/',
         independent_indicator_views.independent_indicator_view, name="independent_indicator"),


    # free board
    path('free_board/',
         free_board_views.free_board_view, name='free_board'),
    path('indicator_page/',
         indicator_views.indicator_view, name='indicator_view'),
    path('ai_indicator_page/',
         ai_indicator_views.indicator_view, name='ai_indicator_view'),
    path('trading_bot_page/',
         trading_bot_views.bot_view, name='trading_bot_view'),

    # view other profiles
    path('profile/<int:user_id>/',
         profile_click_views.profile_detail, name='profile_detail'),

    # view other components
    path('board/<str:board_name>/',
         base_views.index, name='board_view'),

    # fetch time series analysis for indicators page
    path('fetch-time-series-analysis-indicator-page/<str:timeframe>/',
         independent_indicator_views.time_series_analysis, name='time_series_analysis'),

    # NLP related indicator page
    path('nlp_indicators/',
         nlp_dashboard_views.nlp_views, name="nlp_dashboard"),
]

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from common.forms import UserForm, ProfileForm
from common.models import Profile, Attendance, PointTokenTransaction
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from common.forms import CustomPasswordChangeForm
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import timedelta
from django.utils.timezone import now, localtime
from pybo.models import Question, Answer, Comment
from django.core.paginator import Paginator

@login_required(login_url='common:login')
def base(request):
    # account settings base page
    if request.method == "POST":
        # Instantiate the form with the posted data and files (if there are any)
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, '프로필이 정상적으로 업데이트 되었습니다!')
            return redirect("common:settings_base")
    else:
        # Instantiate the form with the current user's profile data
        form = ProfileForm(instance=request.user.profile)
    context = {'settings_type': 'base', 'form': form}
    return render(request, 'common/settings/base.html', context)

@login_required(login_url='common:login')
def account_page(request):
    user = request.user
    profile = user.profile

    user_questions = Question.objects.filter(author=user)
    user_answers = Answer.objects.filter(author=user)
    user_comments = Comment.objects.filter(author=user)

    context = {
        'user': user,
        'profile': profile,
        'questions': user_questions,
        'answers': user_answers,
        'comments': user_comments
    }
    return render(request, 'common/account_page.html', context)

@login_required(login_url='common:login')
def user_questions(request, user_id):
    # Fetch the user based on the passed user_id
    user = get_object_or_404(User, pk=user_id)
    questions_list = Question.objects.filter(author=user).order_by('-create_date')
    # Set up pagination
    paginator = Paginator(questions_list, 10)  # 10 questions per page
    page_number = request.GET.get('page')
    questions = paginator.get_page(page_number)
    profile = user.profile
    return render(request, 'common/user_questions.html', {'questions': questions, 'profile':profile})

@login_required(login_url='common:login')
def user_answers(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    answers_lists = Answer.objects.filter(author=user).order_by('-create_date')
    paginator = Paginator(answers_lists, 10) # 10 answers per page
    page_number = request.GET.get('page')
    answers = paginator.get_page(page_number)
    profile = user.profile
    return render(request, 'common/user_answers.html', {'answers': answers, 'profile': profile})

@login_required(login_url='common:login')
def user_comments(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    comments_list = Comment.objects.filter(author=user).order_by('-create_date')
    paginator = Paginator(comments_list, 10) # 10 comments per page
    page_number = request.GET.get('page')
    comments = paginator.get_page(page_number)
    profile = user.profile
    return render(request, 'common/user_comments.html', {'comments': comments, 'profile': profile})


@login_required(login_url='common:login')
def profile_modify_image(request):
    if request.method == "POST" and 'profile_picture' in request.FILES:
        profile_picture = request.FILES["profile_picture"]
        try:
            if not profile_picture.name.endswith(('.png', '.jpg', '.jpeg')):
                raise ValidationError("Invalid file type: Accepted file types are .png, .jpg, .jpeg")
            width, height = get_image_dimensions(profile_picture)
            max_dimensions = 800
            if width > max_dimensions or height > max_dimensions:
                raise ValidationError("Invalid image size: Max dimensions are 800x800px")
            # Save image to user's profile
            user_profile = request.user.profile  # assumes a related_name of 'profile'
            user_profile.image = profile_picture
            user_profile.save()

            messages.success(request, "Profile picture updated successfully!")
            return redirect('common:settings_base')  # Redirect to a different view after success
        except ValidationError as e:
            messages.error(request, f"Upload failed: {str(e)}")
    elif request.method == "POST":
        messages.error(request, "Something went wrong.")

    return render(request, 'common/settings/profile_picture.html')  # Render the template for image upload


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
        username = form.cleaned_data.get("username")
        raw_password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=raw_password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, "Authentication failed. Please try again.")
    else:
        # GET request
        form = UserForm()
    return render(request, "common/signup.html", {"form": form})

def page_not_found(request, exception):
    return render(request, 'common/404.html', {})

def get_tier(rank, total_users):
    percentile = (rank / total_users) * 100
    if percentile <= 0.01:
        return 'grandmaster', 'grandmaster.png'
    elif percentile <= 0.1:
        return 'challenger', 'challenger.png'
    elif percentile <= 1:
        return 'gold', 'gold.png'
    elif percentile <= 10:
        return 'silver', 'silver.png'
    elif percentile <= 20:
        return 'bronze', 'bronze.png'
    else:
        return 'beginner', 'beginner.png'

def ranking(request):
    user_list = Profile.objects.order_by('-score')
    total_users = user_list.count()
    page = request.GET.get('page', 1)
    paginator = Paginator(user_list, 20)

    try:
        profiles = paginator.page(page)
    except PageNotAnInteger:
        profiles = paginator.page(1)
    except EmptyPage:
        profiles = paginator.page(paginator.num_pages)

    profile_list_with_tier = []
    for index, profile in enumerate(user_list):
        rank = index + 1
        tier, icon = get_tier(rank, total_users)
        if profile in profiles.object_list:
            profile_list_with_tier.append((profile, rank, tier, icon))

    context = {
        'profile_list_with_tier': profile_list_with_tier,
    }
    return render(request, 'common/ranking.html', context)

def point_policy(request):
    return render(request, 'common/point_policy.html', {})

@login_required(login_url="common:login")
def password_reset(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '비밀번호가 정상적으로 변경되었습니다.')
            return redirect('common:settings_base')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'common/settings/password_reset.html', {'form': form})


@login_required(login_url='common:login')
def attendance(request):
    user = request.user
    current_time = timezone.localtime(timezone.now())
    # calculate the number of attendances in the current month
    attendances_this_month = user.attendances.filter(
        timestamp__year = current_time.year,
        timestamp__month = current_time.month
    ).count()

    attended_today = user.attendances.filter(timestamp__date=current_time.date()).exists()

    if request.method == "POST" and not attended_today and attendances_this_month < 25:
        Attendance.objects.create(user=user, timestamp=current_time)
        user.profile.tokens += 2
        user.profile.save()

        PointTokenTransaction.objects.create(
            user=user,
            tokens=2,
            points=0,
            reason="출석체크 보상"
        )

        messages.success(request, "출석체크 완료! 2 토큰을 받았습니다.")
        return redirect('common:attendance')

    context = {
        'attended_today': attended_today,
        'attendances_this_month': attendances_this_month,
        'tokens': user.profile.tokens,
        'now': current_time,
    }
    return render(request, 'common/attendance.html', context)

@login_required(login_url='common:login')
def transaction_detail(request, transaction_id):
    transaction = get_object_or_404(PointTokenTransaction, id=transaction_id, user=request.user)
    transaction_list = PointTokenTransaction.objects.filter(user=request.user).order_by('-timestamp')
    paginator = Paginator(transaction_list, 10) # 10 transactions per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'common/transaction_detail.html', {'transaction':transaction, 'transaction_list':page_obj})

def referral_view(request):
    if not request.user.is_authenticated:
        return redirect('common:login')
    user_profile = request.user.profile
    if request.method == "POST":
        referral_code = request.POST.get('referral_code').strip()
        # check if the user has already used a referral code
        if user_profile.referred_by is not None:
            messages.error(request, '이미 추천 코드를 사용하셨습니다.')
        # check if the referral code is the user's own code
        elif referral_code == user_profile.referral_code:

templates/common/settings/base.html
{% extends "base.html" %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}
<style>
    #profile_base {
        background-color: #f8f8f8;  /* Light grey background */
        padding: 20px;  /* Padding inside the container */
        border-radius: 10px;  /* Rounded corners */
        width: 88%;
        max-width: 888px;
        margin: 20px auto;  /* Centering the container */
    }

    .profile_label {
        font-size: 16px;  /* Font size */
        color: #333;  /* Text color */
        font-weight: bold;  /* Bold text */
        display: block;  /* Block-level element */
        margin-bottom: 5px;  /* Space below the label */
    }

    .profile_info {
        font-size: 14px;  /* Font size */
        color: #555;  /* Text color */
        background-color: #fff;  /* White background */
        padding: 10px;  /* Padding inside the paragraph */
        border-radius: 5px;  /* Slightly rounded corners */
        margin-bottom: 20px;  /* Space below the paragraph */
    }

    .profile_input {
        width: 100%; /* Takes the full width of its container */
        padding: 10px; /* Adds some padding inside the input */
        font-size: 16px; /* Adjusts the font size */
        margin-bottom: 20px; /* Adds some space below the input */
        border-radius: 5px; /* Slightly rounded corners */
        border: 1px solid #ccc; /* Adds a light border */
    }

    .profile_button {
        background-color: #4CAF50; /* Green background */
        color: white; /* White text */
        padding: 12px 20px; /* Padding */
        border: none; /* No border */
        border-radius: 5px; /* Rounded corners */
        cursor: pointer; /* Pointer cursor on hover */
        width: 100%; /* Takes the full width of its container */
    }

    .profile_button:hover {
        background-color: #45a049; /* Darker green on hover */
    }

    #messages {
        width: 88%;
        max-width: 888px;
        margin: 20px auto 0;
        border-radius: 5px;
    }

    #messages p {
        padding: 15px;
        margin: 0;
        border-radius: 5px;
        color: white;
        font-size: 16px;
    }

    #messages p.info {
        background-color: #4CAF50; /* Green background for info */
    }

    #messages p.error {
        background-color: #f44336; /* Red background for errors */
    }

    #messages p.warning {
        background-color: #ff9800; /* Orange background for warnings */
    }

    #messages p.success {
        background-color: #4CAF50; /* Green background for success */
    }
</style>


<div class="col-md-10">
    {% if messages %}
        <div id="messages">
            {% for message in messages %}
                <p class="{{ message.tags }}">{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'common:settings_base' %}">기본정보</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'common:settings_image' %}">프로필 이미지</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'common:password_reset' %}">비밀번호 변경</a>
        </li>
    </ul>
    <div id="profile_base">
    <label for="email" class="profile_label">이메일</label>
    <p id="email" class="profile_info mb-4">{{ user.email }}</p>

    <label for="username" class="profile_label">유저 닉네임 (ID)</label>
    <p id="username" class="profile_info mb-4">{{ user.username }}</p>

    <form method="post" action="{% url 'common:settings_base' %}">
        {% csrf_token %}
        <label class="profile_label">한줄 소개</label>
        <input type="text" name="intro" class="profile_input mb-4" placeholder="여기에 한줄소개를 작성하세요" value="{{ user.profile.intro }}">

        <label class="profile_label">Instagram</label>
        <input type="url" name="instagram_url" class="profile_input mb-4" placeholder="Instagram URL" value="{{ user.profile.instagram_url }}">

        <label class="profile_label">Twitter</label>
        <input type="url" name="twitter_url" class="profile_input mb-4" placeholder="Twitter URL" value="{{ user.profile.twitter_url }}">

        <label class="profile_label">YouTube</label>
        <input type="url" name="youtube_url" class="profile_input mb-4" placeholder="YouTube URL" value="{{ user.profile.youtube_url }}">

        <label class="profile_label">Personal Website</label>
        <input type="url" name="personal_url" class="profile_input mb-4" placeholder="Personal URL" value="{{ user.profile.personal_url }}">
        <button type="submit">저장하기</button>
    </form>


</div>

</div>
{% endblock %}

templates/common/settings/password_reset.html
{% extends "base.html" %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}
<style>
    #profile_base {
        background-color: #f8f8f8;
        padding: 20px;
        border-radius: 10px;
        width: 88%;
        max-width: 888px;
        margin: 20px auto;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    }

    .profile_label {
        font-size: 18px;
        color: #333;
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .profile_info {
        font-size: 14px;
        color: #555;
        background-color: #fff;
        padding: 10px;
        border-radius: 5px;
        margin-bottom: 20px;
        box-shadow: 0 2px 4px 0 rgba(0,0,0,0.1);
    }

    .profile_input {
        width: 100%;
        padding: 10px;
        font-size: 16px;
        margin-bottom: 20px;
        border-radius: 5px;
        border: 1px solid #ccc;
        box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
    }

    .profile_button {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        transition: background-color 0.3s, box-shadow 0.3s;
    }

    .profile_button:hover {
        background-color: #45a049;
        box-shadow: 0 6px 8px rgba(0,0,0,0.15);
    }

    #messages {
        width: 88%;
        max-width: 888px;
        margin: 20px auto 0;
        border-radius: 5px;
    }

    #messages p {
        padding: 15px;
        margin: 0;
        border-radius: 5px;
        color: white;
        font-size: 16px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    #messages p.info {
        background-color: #4CAF50;
    }

    #messages p.error {
        background-color: #f44336;
    }

    #messages p.warning {
        background-color: #ff9800;
    }

    #messages p.success {
        background-color: #4CAF50;
    }
</style>

<div class="col-md-10">
    {% if messages %}
        <div id="messages">
            {% for message in messages %}
                <p class="{{ message.tags }}">{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'common:settings_base' %}">기본정보</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'common:settings_image' %}">프로필 이미지</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'common:password_reset' %}">비밀번호 변경</a>
        </li>
    </ul>
    <div id="profile_base">
        <h4>비밀번호 변경</h4>
        <br>
        <form method="post">
            {% csrf_token %}
            <label for="{{ form.old_password.id_for_label }}" class="profile_label">{{ form.old_password.label }}</label>
            <input type="password" name="{{ form.old_password.name }}" class="profile_input" id="{{ form.old_password.id_for_label }}" required {{ form.old_password.field.widget.attrs }}>

            <label for="{{ form.new_password1.id_for_label }}" class="profile_label">{{ form.new_password1.label }}</label>
            <input type="password" name="{{ form.new_password1.name }}" class="profile_input" id="{{ form.new_password1.id_for_label }}" required {{ form.new_password1.field.widget.attrs }}>

            <label for="{{ form.new_password2.id_for_label }}" class="profile_label">{{ form.new_password2.label }}</label>
            <input type="password" name="{{ form.new_password2.name }}" class="profile_input" id="{{ form.new_password2.id_for_label }}" required {{ form.new_password2.field.widget.attrs }}>

            <button type="submit" class="profile_button">변경하기</button>
        </form>
    </div>
</div>
{% endblock %}

templates/common/settings/profile_picture.html
{% extends "base.html" %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock %}

{% block content %}
<style>
    #profile_base {
        background-color: #f8f8f8;  /* Light grey background */
        padding: 20px;  /* Padding inside the container */
        border-radius: 10px;  /* Rounded corners */
        width: 88%;
        max-width: 888px;
        margin: 20px auto;  /* Centering the container */
    }

    .profile_label {
        font-size: 16px;  /* Font size */
        color: #333;  /* Text color */
        font-weight: bold;  /* Bold text */
        display: block;  /* Block-level element */
        margin-bottom: 5px;  /* Space below the label */
    }

    .profile_info {
        font-size: 14px;  /* Font size */
        color: #555;  /* Text color */
        background-color: #fff;  /* White background */
        padding: 10px;  /* Padding inside the paragraph */
        border-radius: 5px;  /* Slightly rounded corners */
        margin-bottom: 20px;  /* Space below the paragraph */
    }

    .profile_input {
        width: 100%; /* Takes the full width of its container */
        padding: 10px; /* Adds some padding inside the input */
        font-size: 16px; /* Adjusts the font size */
        margin-bottom: 20px; /* Adds some space below the input */
        border-radius: 5px; /* Slightly rounded corners */
        border: 1px solid #ccc; /* Adds a light border */
    }

    .profile_button {
        background-color: #4CAF50; /* Green background */
        color: white; /* White text */
        padding: 12px 20px; /* Padding */
        border: none; /* No border */
        border-radius: 5px; /* Rounded corners */
        cursor: pointer; /* Pointer cursor on hover */
        width: 100%; /* Takes the full width of its container */
    }

    .profile_button:hover {
        background-color: #45a049; /* Darker green on hover */
    }

    #messages {
        width: 88%;
        max-width: 888px;
        margin: 20px auto 0;
        border-radius: 5px;
    }

    #messages p {
        padding: 15px;
        margin: 0;
        border-radius: 5px;
        color: white;
        font-size: 16px;
    }

    #messages p.info {
        background-color: #4CAF50; /* Green background for info */
    }

    #messages p.error {
        background-color: #f44336; /* Red background for errors */
    }

    #messages p.warning {
        background-color: #ff9800; /* Orange background for warnings */
    }

    #messages p.success {
        background-color: #4CAF50; /* Green background for success */
    }
</style>


<div class="col-md-10">
    {% if messages %}
        <div id="messages">
            {% for message in messages %}
                <p class="{{ message.tags }}">{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'common:settings_base' %}">기본정보</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'common:settings_image' %}">프로필 이미지</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'common:password_reset' %}">비밀번호 변경</a>
        </li>
    </ul>
    <div id="profile_base">
        <p>프로필 이미지 설정하기</p>
        <form method="post" enctype="multipart/form-data" action="{% url 'common:settings_image' %}">
            {% csrf_token %}
            <label for="profile_picture" class="profile_label">이미지를 고르세요:</label>
            <input type="file" name="profile_picture" id="profile_picture" class="profile_input" accept="image/*">
            <button type="submit" class="profile_button">이미지 업로드하기</button>
        </form>
    </div>

</div>
{% endblock %}