config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings
from django.conf.urls.static import static
from pybo.views import indicator_views, ai_indicator_views, profile_click_views, independent_indicator_views, nlp_dashboard_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
    # crypto fear greed index GPT response
    path('fetch_ai_analysis/',
         indicator_views.fetch_ai_analysis, name='fetch_ai_analysis'),
    path('fetch_ai_analysis_global/',
         indicator_views.fetch_ai_analysis_global, name='fetch_ai_analysis_global'),
    path('fetch_ai_technical/',
         indicator_views.fetch_ai_technical, name='fetch_ai_technical'),
    path('fetch_ai_corr/',
         ai_indicator_views.fetch_ai_corr, name='fetch_ai_corr'),
    path('fetch_forecast/',
         ai_indicator_views.time_series_views, name='fetch_forecast'),
    path('search_news/',
         ai_indicator_views.search_news, name='search_news'),
    path('fetch-time-series-analysis-indicator-page/<str:timeframe>/',
         independent_indicator_views.time_series_analysis, name='time_series_analysis'),
    path('fetch-gpt-analysis/<str:timeframe>/',
         independent_indicator_views.fetch_ai_analysis, name='fetch_ai_analysis'),
    path('news_similarity/',
         nlp_dashboard_views.search_news, name="nlp_dashboard_search_news"),
    path('search_chart_pattern/',
         nlp_dashboard_views.search_chart_pattern, name="nlp_dashboard_search_chart_patterns"),
]

handler404 = 'common.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views, free_board_views, indicator_views, profile_click_views, component_views, ai_indicator_views, trading_bot_views, independent_indicator_views, nlp_dashboard_views
app_name = "pybo"

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name="index"),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    #path('question/create/',
    #     question_views.question_create, name='question_create'),
    path('question/create/<str:board_name>/',
         question_views.question_create, name="question_create"),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/questions/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/',
         vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/',
         vote_views.vote_answer, name='vote_answer'),

    # independent indicators
    path('independent_indicators/',
         independent_indicator_views.independent_indicator_view, name="independent_indicator"),


    # free board
    path('free_board/',
         free_board_views.free_board_view, name='free_board'),
    path('indicator_page/',
         indicator_views.indicator_view, name='indicator_view'),
    path('ai_indicator_page/',
         ai_indicator_views.indicator_view, name='ai_indicator_view'),
    path('trading_bot_page/',
         trading_bot_views.bot_view, name='trading_bot_view'),

    # view other profiles
    path('profile/<int:user_id>/',
         profile_click_views.profile_detail, name='profile_detail'),

    # view other components
    path('board/<str:board_name>/',
         base_views.index, name='board_view'),

    # fetch time series analysis for indicators page
    path('fetch-time-series-analysis-indicator-page/<str:timeframe>/',
         independent_indicator_views.time_series_analysis, name='time_series_analysis'),

    # NLP related indicator page
    path('nlp_indicators/',
         nlp_dashboard_views.nlp_views, name="nlp_dashboard"),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Board(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    def __str__(self):
        return self.name

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='freeboard_questions', null=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question') # add voter
    initial_price = models.DecimalField(max_digits=20, decimal_places=8, null=True, blank=True)
    prediction_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.subject
    def save(self, *args, **kwargs):
        is_new = self.pk is None  # Check if the question is new
        super().save(*args, **kwargs)  # Call the super class's save method
        if is_new:  # If the question is new, then update the score
            self.author.profile.score += 5 if self.board.name == "perceptive" else 3
            self.author.profile.save()
    def delete(self, *args, **kwargs):
        if self.board.name == "perceptive":
            self.author.profile.score -= 5
        else:
            self.author.profile.score -= 3
        self.author.profile.save()
        super().delete(*args, **kwargs)

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            if self.question.board.name == "perceptive":
                self.author.profile.score += 4
            else:
                self.author.profile.score += 2
            self.author.profile.save()

    def delete(self, *args, **kwargs):
        if self.question.board.name == "perceptive":
            self.author.profile.score -= 4
        else:
            self.author.profile.score -= 2
        self.author.profile.save()
        super().delete(*args, **kwargs)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)
    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            self.author.profile.score += 1
            self.author.profile.save()

    def delete(self, *args, **kwargs):
        self.author.profile.score -= 1
        self.author.profile.save()
        super().delete(*args, **kwargs)

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["subject", "content"]  # Removed "board" here
        labels = {
            "subject": "제목",
            "content": "내용",
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            "content": "답변내용",
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            "content": "댓글내용",
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..forms import AnswerForm
from ..models import Question, Answer
from common.models import PointTokenTransaction
@login_required(login_url="common:login")

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user # 추가한 속성 author 적용
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            if answer.question.board.name == "perceptive":
                points_for_question = 4
            elif answer.question.board.name in ["free_board", "technical_blog", "trading_blog"]:
                points_for_question = 2
            eng_to_kor_name = {'perceptive': '관점공유 게시판', 'free_board': '자유게시판', 'technical_blog': '기술 블로그',
                               'trading_blog': '트레이딩 블로그'}
            kor_board_name = eng_to_kor_name[answer.question.board.name]
            PointTokenTransaction.objects.create(
                user=request.user,
                points=points_for_question,
                tokens=0,  # Assuming you only want to deal with points
                reason=f"{kor_board_name}에 답글 포스팅"
            )
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
            # return redirect("pybo:detail", question_id=question_id)
    else:
        form = AnswerForm()
    context = {"question": question, "form": form}
    return render(request, "pybo/question_detail.html", context)

@login_required(login_url="common:login")
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, "수정권한이 없습니다!")
        return redirect("pybo:detail", question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
            # return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {"answer":answer, "form":form}
    return render(request, "pybo/answer_form.html", context)

@login_required(login_url="common:login")
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, "삭제권한이 없습니다!")
    else:
        answer.delete()
        if answer.question.board.name == "perceptive":
            points_for_question = -4
        elif answer.question.board.name in ["free_board", "technical_blog", "trading_blog"]:
            points_for_question = -2
        eng_to_kor_name = {'perceptive': '관점공유 게시판', 'free_board': '자유게시판', 'technical_blog': '기술 블로그',
                           'trading_blog': '트레이딩 블로그'}
        kor_board_name = eng_to_kor_name[answer.question.board.name]
        PointTokenTransaction.objects.create(
            user=request.user,
            points=points_for_question,
            tokens=0,  # Assuming you only want to deal with points
            reason=f"{kor_board_name}에 답글 삭제"
        )
    return redirect("pybo:detail", question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Question, Board
from django.db.models import Q, Count


def index(request, board_name="perceptive"):
    # If directly accessing the main URL, redirect to the perceptive board
    if not board_name:
        return redirect('pybo:board_view', board_name='perceptive')

    board = get_object_or_404(Board, name=board_name)
    question_list = Question.objects.filter(board=board)

    page = request.GET.get("page", "1")  # page
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get("so", "recent")  # sort order

    # 정렬
    if so == "recommend":
        question_list = question_list.annotate(
            num_voter=Count('voter')).order_by("-num_voter", "-create_date")
    elif so == "popular":
        question_list = question_list.annotate(
            num_answer=Count('answer')).order_by("-num_answer", "-create_date")
    else:  # recent
        question_list = question_list.order_by("-create_date")

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {"question_list": page_obj, "page": page, "kw": kw, "board_name": board_name}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    ''' Print out question content '''
    question = get_object_or_404(Question, pk=question_id)
    context = {"question": question}
    return render(request, "pybo/question_detail.html", context)

pybo/views/component_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question, Board
from django.core.paginator import Paginator

def component_list(request, board_name=None):
    if board_name:
        board = get_object_or_404(Board, name=board_name)
        question_list = Question.objects.filter(board=board)
    else:
        question_list = Question.objects.all()

    # Paginate the question_list just like in the index view
    page = request.GET.get("page", "1")
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {
        'question_list': page_obj,  # Pass the Page object, not the QuerySet
        'board_name': board_name,
    }

    return render(request, 'pybo/question_list.html', context)

pybo/views/free_board_views.py
from django.shortcuts import render

def free_board_view(request):
    return render(request, 'free_board_views.html')

pybo/views/profile_click_views.py
from django.shortcuts import render, get_object_or_404
from common.models import Profile, Question, Answer, Comment
from django.contrib.auth.models import User

def profile_detail(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    profile = get_object_or_404(Profile, user=user)

    # Fetch user's questions, answers, and comments
    user_questions = Question.objects.filter(author=user)
    user_answers = Answer.objects.filter(author=user)
    user_comments = Comment.objects.filter(author=user)

    context = {
        'profile': profile,
        'user_questions': user_questions,
        'user_answers': user_answers,
        'user_comments': user_comments
    }
    return render(request, "profile_detail.html", context)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom- pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content" rows="3">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">

    <!-- MathJax Configuration -->
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
          tex2jax: {
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true
          }
        });
    </script>
    <!-- Include MathJax Script -->
    <script type="text/javascript" async
      src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>

<div class="container my-3">
    <!-- 사용자 요류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천 영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{question.voter.count}}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <!-- 기존 내용 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">
                        {{ question.content|mark }}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2"><a href="{% url 'pybo:profile_detail' question.author.id %}">{{ question.author.username }}</a></div>
                            <div> {{ question.create_date }} </div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        {% if question.board.name != 'perceptive' %}
                        <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">edit</a>
                        {% endif %}
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">delete</a>
                    </div>
                    {% endif %}
                    <!-- 질문 댓글 start -->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in question.comment_set.all %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line; font-size: 18px;">{{ comment.content }}</span>
                            <span>
                                - <a href="{% url 'pybo:profile_detail' comment.author.id %}">{{ comment.author }}</a>, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">edit</a>
                            <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_question' comment.id %}">delete</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_question' question.id %}" class="small"><small>댓글 추가...</small></a>
                    </div>
                    <!-- 질문 댓글 end -->
                    </div>
                </div>
            </div>
        </div>
    <h5 class="border-bottom my-3 py-2">
        {{question.answer_set.count}}개의 답글이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ answer.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">
                        {{ answer.content|mark }}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2"><a href="{% url 'pybo:profile_detail' answer.author.id %}">{{ answer.author.username }}</a></div>
                            <div> {{ answer.create_date }} </div>
                        </div>
                    </div>
                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">edit</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">delete</a>
                    </div>
                    {% endif %}
                    <!-- 답변 댓글 start -->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in answer.comment_set.all %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line; font-size: 18px;">{{ comment.content }}</span>
                            <span>
                                - <a href="{% url 'pybo:profile_detail' comment.author.id %}">{{ comment.author }}</a>, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">edit</a>
                            <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">delete</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small"><small>댓글 추가...</small></a>
                    </div>
                    <!-- 답변 댓글 end -->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id  %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content"
                      {% if not user.is_authenticated %}disabled{% endif %}
                      class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $(".delete").on("click", function(){
            if(confirm("are you sure you want to delete this post?")){
                location.href = $(this).data("uri");
            }
        });
        $(".recommend").on("click", function(){
            if(confirm("do you want to upvote?")){
                location.href = $(this).data("uri");
            }
        });
    });
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2"> 게시글 등록 </h5>
    <!-- Messages display start -->
    {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
    <!-- Messages display end -->

    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류 표시 start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <!-- 오류 표시 end -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
            <p>Word Count: <span id="wordCount">0</span></p>
        </div>

        {% if is_perceptive_board %}
            <div class="form-group">
                <label for="crypto">Crypto</label>
                <select class="form-control" name="crypto" id="crypto" required>
                    <option value="">Choose...</option>
                    <option value="BTC">BTC</option>
                    <option value="ETH">ETH</option>
                    <!-- Add other crypto options here -->
                </select>
            </div>
            <div class="form-group">
                <label for="duration">Duration</label>
                <select class="form-control" name="duration" id="duration" required>
                    <option value="">Choose...</option>
                    <option value="1 hour">1 hour</option>
                    <option value="2 hours">2 hours</option>
                    <option value="4 hours">4 hours</option>
                    <option value="6 hours">6 hours</option>
                    <option value="8 hours">8 hours</option>
                    <option value="12 hours">12 hours</option>
                    <option value="24 hours">24 hours</option>
                    <option value="one week">one week</option>
                    <option value="one month">one month</option>
                    <option value="one year">one year</option>
                </select>
            </div>
            <div class="form-group">
                <label for="direction">Direction</label>
                <select class="form-control" name="direction" id="direction" required>
                    <option value="">Choose...</option>
                    <option value="bullish">bullish</option>
                    <option value="bearish">bearish</option>
                </select>
            </div>
            <div class="form-group">
                <label for="price_change">Price Change</label>
                <input type="text" class="form-control" name="price_change" id="price_change" placeholder="e.g. +5%, -3%" required>
            </div>
        {% endif %}

        <button type="submit" class="btn btn-primary"> 저장하기 </button>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    document.getElementById('content').addEventListener('input', function(e) {
        var text = e.target.value;
        // Remove leading/trailing whitespaces and split the string by spaces
        var words = text.trim().split(/\s+/);
        // Update word count
        document.getElementById('wordCount').innerText = words.length;
    });
</script>
{% endblock script %}