common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'common'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="common/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),

    # account settings
    path("settings/base/", views.base, name="settings_base"),
    # path("settings/password_change/", settings_views.PasswordChangeView.as_view(), name="password_change),
    path("settings/image/", views.profile_modify_image, name="settings_image"),
    # path("settings/image/delete/", settings_views.profile_image_delete, name="settings_image_delete"),
    path('settings/password_reset/', views.password_reset, name='password_reset'),

    # account page
    path("account_page/", views.account_page, name="account_page"),

    # ranking page
    path('ranking/', views.ranking, name='ranking'),

    # point policy page
    path("point_policy/", views.point_policy, name="point_policy"),

    # attendance page
    path('attendance/', views.attendance, name='attendance'),

    path('transactions/<int:transaction_id>/', views.transaction_detail, name='transaction_detail'),

    path('referral/', views.referral_view, name='referral'),

    path('user/<int:user_id>/questions/', views.user_questions, name='user_questions'),

    path('user/<int:user_id>/answers/', views.user_answers, name='user_answers'),

    path('user/<int:user_id>/comments/', views.user_comments, name='user_comments'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings
from django.conf.urls.static import static
from pybo.views import indicator_views, ai_indicator_views, profile_click_views, independent_indicator_views, nlp_dashboard_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
    # crypto fear greed index GPT response
    path('fetch_ai_analysis/',
         indicator_views.fetch_ai_analysis, name='fetch_ai_analysis'),
    path('fetch_ai_analysis_global/',
         indicator_views.fetch_ai_analysis_global, name='fetch_ai_analysis_global'),
    path('fetch_ai_technical/',
         indicator_views.fetch_ai_technical, name='fetch_ai_technical'),
    path('fetch_ai_corr/',
         ai_indicator_views.fetch_ai_corr, name='fetch_ai_corr'),
    path('fetch_forecast/',
         ai_indicator_views.time_series_views, name='fetch_forecast'),
    path('search_news/',
         ai_indicator_views.search_news, name='search_news'),
    path('fetch-time-series-analysis-indicator-page/<str:timeframe>/',
         independent_indicator_views.time_series_analysis, name='time_series_analysis'),
    path('fetch-gpt-analysis/<str:timeframe>/',
         independent_indicator_views.fetch_ai_analysis, name='fetch_ai_analysis'),
    path('news_similarity/',
         nlp_dashboard_views.search_news, name="nlp_dashboard_search_news"),
    path('search_chart_pattern/',
         nlp_dashboard_views.search_chart_pattern, name="nlp_dashboard_search_chart_patterns"),
]

handler404 = 'common.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views, free_board_views, indicator_views, profile_click_views, component_views, ai_indicator_views, trading_bot_views, independent_indicator_views, nlp_dashboard_views
app_name = "pybo"

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name="index"),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    #path('question/create/',
    #     question_views.question_create, name='question_create'),
    path('question/create/<str:board_name>/',
         question_views.question_create, name="question_create"),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/questions/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/',
         vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/',
         vote_views.vote_answer, name='vote_answer'),

    # independent indicators
    path('independent_indicators/',
         independent_indicator_views.independent_indicator_view, name="independent_indicator"),


    # free board
    path('free_board/',
         free_board_views.free_board_view, name='free_board'),
    path('indicator_page/',
         indicator_views.indicator_view, name='indicator_view'),
    path('ai_indicator_page/',
         ai_indicator_views.indicator_view, name='ai_indicator_view'),
    path('trading_bot_page/',
         trading_bot_views.bot_view, name='trading_bot_view'),

    # view other profiles
    path('profile/<int:user_id>/',
         profile_click_views.profile_detail, name='profile_detail'),

    # view other components
    path('board/<str:board_name>/',
         base_views.index, name='board_view'),

    # fetch time series analysis for indicators page
    path('fetch-time-series-analysis-indicator-page/<str:timeframe>/',
         independent_indicator_views.time_series_analysis, name='time_series_analysis'),

    # NLP related indicator page
    path('nlp_indicators/',
         nlp_dashboard_views.nlp_views, name="nlp_dashboard"),
]

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from common.forms import UserForm, ProfileForm
from common.models import Profile, Attendance, PointTokenTransaction
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from common.forms import CustomPasswordChangeForm
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import timedelta
from django.utils.timezone import now, localtime
from pybo.models import Question, Answer, Comment
from django.core.paginator import Paginator

@login_required(login_url='common:login')
def base(request):
    # account settings base page
    if request.method == "POST":
        # Instantiate the form with the posted data and files (if there are any)
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, '프로필이 정상적으로 업데이트 되었습니다!')
            return redirect("common:settings_base")
    else:
        # Instantiate the form with the current user's profile data
        form = ProfileForm(instance=request.user.profile)
    context = {'settings_type': 'base', 'form': form}
    return render(request, 'common/settings/base.html', context)

@login_required(login_url='common:login')
def account_page(request):
    user = request.user
    profile = user.profile

    user_questions = Question.objects.filter(author=user)
    user_answers = Answer.objects.filter(author=user)
    user_comments = Comment.objects.filter(author=user)

    context = {
        'user': user,
        'profile': profile,
        'questions': user_questions,
        'answers': user_answers,
        'comments': user_comments
    }
    return render(request, 'common/account_page.html', context)

@login_required(login_url='common:login')
def user_questions(request, user_id):
    # Fetch the user based on the passed user_id
    user = get_object_or_404(User, pk=user_id)
    questions_list = Question.objects.filter(author=user).order_by('-create_date')
    # Set up pagination
    paginator = Paginator(questions_list, 10)  # 10 questions per page
    page_number = request.GET.get('page')
    questions = paginator.get_page(page_number)
    profile = user.profile
    return render(request, 'common/user_questions.html', {'questions': questions, 'profile':profile})

@login_required(login_url='common:login')
def user_answers(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    answers_lists = Answer.objects.filter(author=user).order_by('-create_date')
    paginator = Paginator(answers_lists, 10) # 10 answers per page
    page_number = request.GET.get('page')
    answers = paginator.get_page(page_number)
    profile = user.profile
    return render(request, 'common/user_answers.html', {'answers': answers, 'profile': profile})

@login_required(login_url='common:login')
def user_comments(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    comments_list = Comment.objects.filter(author=user).order_by('-create_date')
    paginator = Paginator(comments_list, 10) # 10 comments per page
    page_number = request.GET.get('page')
    comments = paginator.get_page(page_number)
    profile = user.profile
    return render(request, 'common/user_comments.html', {'comments': comments, 'profile': profile})


@login_required(login_url='common:login')
def profile_modify_image(request):
    if request.method == "POST" and 'profile_picture' in request.FILES:
        profile_picture = request.FILES["profile_picture"]
        try:
            if not profile_picture.name.endswith(('.png', '.jpg', '.jpeg')):
                raise ValidationError("Invalid file type: Accepted file types are .png, .jpg, .jpeg")
            width, height = get_image_dimensions(profile_picture)
            max_dimensions = 800
            if width > max_dimensions or height > max_dimensions:
                raise ValidationError("Invalid image size: Max dimensions are 800x800px")
            # Save image to user's profile
            user_profile = request.user.profile  # assumes a related_name of 'profile'
            user_profile.image = profile_picture
            user_profile.save()

            messages.success(request, "Profile picture updated successfully!")
            return redirect('common:settings_base')  # Redirect to a different view after success
        except ValidationError as e:
            messages.error(request, f"Upload failed: {str(e)}")
    elif request.method == "POST":
        messages.error(request, "Something went wrong.")

    return render(request, 'common/settings/profile_picture.html')  # Render the template for image upload


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
        username = form.cleaned_data.get("username")
        raw_password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=raw_password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, "Authentication failed. Please try again.")
    else:
        # GET request
        form = UserForm()
    return render(request, "common/signup.html", {"form": form})

def page_not_found(request, exception):
    return render(request, 'common/404.html', {})

def get_tier(rank, total_users):
    percentile = (rank / total_users) * 100
    if percentile <= 0.01:
        return 'grandmaster', 'grandmaster.png'
    elif percentile <= 0.1:
        return 'challenger', 'challenger.png'
    elif percentile <= 1:
        return 'gold', 'gold.png'
    elif percentile <= 10:
        return 'silver', 'silver.png'
    elif percentile <= 20:
        return 'bronze', 'bronze.png'
    else:
        return 'beginner', 'beginner.png'

def ranking(request):
    user_list = Profile.objects.order_by('-score')
    total_users = user_list.count()
    page = request.GET.get('page', 1)
    paginator = Paginator(user_list, 20)

    try:
        profiles = paginator.page(page)
    except PageNotAnInteger:
        profiles = paginator.page(1)
    except EmptyPage:
        profiles = paginator.page(paginator.num_pages)

    profile_list_with_tier = []
    for index, profile in enumerate(user_list):
        rank = index + 1
        tier, icon = get_tier(rank, total_users)
        if profile in profiles.object_list:
            profile_list_with_tier.append((profile, rank, tier, icon))

    context = {
        'profile_list_with_tier': profile_list_with_tier,
    }
    return render(request, 'common/ranking.html', context)

def point_policy(request):
    return render(request, 'common/point_policy.html', {})

@login_required(login_url="common:login")
def password_reset(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '비밀번호가 정상적으로 변경되었습니다.')
            return redirect('common:settings_base')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'common/settings/password_reset.html', {'form': form})


@login_required(login_url='common:login')
def attendance(request):
    user = request.user
    current_time = timezone.localtime(timezone.now())
    # calculate the number of attendances in the current month
    attendances_this_month = user.attendances.filter(
        timestamp__year = current_time.year,
        timestamp__month = current_time.month
    ).count()

    attended_today = user.attendances.filter(timestamp__date=current_time.date()).exists()

    if request.method == "POST" and not attended_today and attendances_this_month < 25:
        Attendance.objects.create(user=user, timestamp=current_time)
        user.profile.tokens += 2
        user.profile.save()

        PointTokenTransaction.objects.create(
            user=user,
            tokens=2,
            points=0,
            reason="출석체크 보상"
        )

        messages.success(request, "출석체크 완료! 2 토큰을 받았습니다.")
        return redirect('common:attendance')

    context = {
        'attended_today': attended_today,
        'attendances_this_month': attendances_this_month,
        'tokens': user.profile.tokens,
        'now': current_time,
    }
    return render(request, 'common/attendance.html', context)

@login_required(login_url='common:login')
def transaction_detail(request, transaction_id):
    transaction = get_object_or_404(PointTokenTransaction, id=transaction_id, user=request.user)
    transaction_list = PointTokenTransaction.objects.filter(user=request.user).order_by('-timestamp')
    paginator = Paginator(transaction_list, 10) # 10 transactions per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'common/transaction_detail.html', {'transaction':transaction, 'transaction_list':page_obj})

def referral_view(request):
    if not request.user.is_authenticated:
        return redirect('common:login')
    user_profile = request.user.profile
    if request.method == "POST":
        referral_code = request.POST.get('referral_code').strip()
        # check if the user has already used a referral code
        if user_profile.referred_by is not None:
            messages.error(request, '이미 추천 코드를 사용하셨습니다.')
        # check if the referral code is the user's own code
        elif referral_code == user_profile.referral_code:

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>login</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                or <a href="{% url 'common:signup' %}">create an account</a>
            </span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <!-- 로그인 성공 후 이동되는 URL -->
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username"><strong>user ID</strong></label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password"><strong>password</strong></label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">login</button>
    </form>
</div>
{% endblock %}

templates/common/point_policy.html
{% extends 'base.html' %}
{% load static %}
{% load pybo_filter %}
{% block content %}
<style>
    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: #f1f1f1;
        text-align: center;
        padding: 10px 0;  /* Adjusted padding to make it slimmer */
        font-size: 0.8rem;  /* You can adjust the font size accordingly */
    }

    .container.my-3 {
        padding-bottom: 50px;  /* Adjusted space to ensure no overlap with the footer */
    }

    .card {
        background-color: #ffffff;
        border: 1px solid #e0e0e0;
        border-radius: 10px;
        padding: 20px;
        margin: 20px 0;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    h2 {
        color: #4CAF50;
        font-size: 2.5em;
        margin-bottom: 20px;
    }
    p {
        font-size: 1.2em;
        color: #666666;
        margin: 0 0 10px;
    }
    .list {
        list-style: none;
        padding: 0;
    }
    .list li {
        margin-bottom: 10px;
        font-size: 1.2em;
    }
    .score {
        font-weight: 700;
        color: #4CAF50;
    }
</style>

<!-- Sidebar -->
<div class="col-md-2">
    <div class="list-group">
        <a href="{% url 'pybo:board_view' 'perceptive' %}" class="list-group-item list-group-item-action sidebar-item">관점공유 게시판</a>
        <a href="{% url 'pybo:board_view' 'free_board' %}" class="list-group-item list-group-item-action sidebar-item">자유게시판</a>
        <a href="{% url 'pybo:board_view' 'technical_blog' %}" class="list-group-item list-group-item-action sidebar-item">기술 블로그</a>
        <a href="{% url 'pybo:board_view' 'trading_blog' %}" class="list-group-item list-group-item-action sidebar-item">트레이딩 블로그</a>
        <a href="{% url 'pybo:indicator_view' %}" class="list-group-item list-group-item-action sidebar-item">기술 지표 페이지</a>
        <a href="{% url 'pybo:ai_indicator_view' %}" class="list-group-item list-group-item-action sidebar-item">AI 지표 페이지</a>
        <a href="{% url 'pybo:free_board' %}" class="list-group-item list-group-item-action sidebar-item">투자봇 페이지</a>
        <a href="{% url 'pybo:free_board' %}" class="list-group-item list-group-item-action sidebar-item">대회</a>
    </div>
</div>

<div class="col-md-10">
  <div class="container my-3">
    <div class="card">
        <small><a href="{% url 'common:ranking' %}">Back to user ranking</a></small>
        <h2>포인트 정책</h2>
        <ul class="list">
            <li>관점공유 게시판에 글을 작성하면 <span class="score">5점</span>이 부여됩니다.</li>
            <li>자유게시판, 기술 블로그, 트레이딩 블로그에 글을 작성하면 <span class="score">3점</span>이 부여됩니다.</li>
            <li>관점공유 게시판에 답글을 작성하면 <span class="score">4점</span>이 부여됩니다.</li>
            <li>자유게시판, 기술 블로그, 트레이딩 블로그에 답글을 작성하면 <span class="score">2점</span>이 부여됩니다.</li>
            <li>댓글을 작성하면 <span class="score">1점</span>이 부여됩니다.</li>
            <li>좋아요를 받으면 <span class="score">2점</span>이 부여됩니다.</li>
            <li>좋아요를 주면 <span class="score">1점</span>이 부여됩니다.</li>
        </ul>
    </div>
    <div class="card">
        <h2>티어 시스템</h2>
        <ul class="list">
            <li><img src="{% static 'beginner.png' %}" alt="beginner" style="width:20px; vertical-align: middle;">Beginner: 알파비트에 가입하고 참여를 많이 하지 않은 유저들에게 부여됩니다.</li>
            <li><img src="{% static 'bronze.png' %}" alt="bronze" style="width:20px; vertical-align: middle;">Bronze: 상위 <span class="score">20%</span>의 유저들에게 부여됩니다.</li>
            <li><img src="{% static 'silver.png' %}" alt="silver" style="width:20px; vertical-align: middle;">Silver: 상위 <span class="score">10%</span>의 유저들에게 부여됩니다.</li>
            <li><img src="{% static 'gold.png' %}" alt="gold" style="width:20px; vertical-align: middle;">Gold: 상위 <span class="score">1%</span>의 유저들에게 부여됩니다.</li>
            <li><img src="{% static 'challenger.png' %}" alt="challenger" style="width:20px; vertical-align: middle;">Challenger: 상위 <span class="score">0.1%</span>의 유저들에게 부여됩니다.</li>
            <li><img src="{% static 'grandmaster.png' %}" alt="grandmaster" style="width:20px; vertical-align: middle;">Grandmaster: 상위 <span class="score">0.01%</span>의 유저들에게 부여됩니다.</li>
        </ul>
    </div>
    <div class="card">
        <h2>APB 토큰 지급 시스템</h2>
        <ul class="list">
            <li>Bronze 티어는 매달 <span class="score">10개</span>가 부여됩니다.</li>
            <li>Silver 티어는 매달 <span class="score">20개</span>가 부여됩니다.</li>
            <li>Gold 티어는 매달 <span class="score">30개</span>가 부여됩니다.</li>
            <li>Challenger 티어는 매달 <span class="score">60개</span>가 부여됩니다.</li>
            <li>Grandmaster 티어는 매달 <span class="score">100개</span>가 부여됩니다.</li>
            <li>출석체크를 통해 한달에 최대 <span class="score">50개</span>를 모을 수 있습니다.</li>
            <li>관점공유 게시판에 작성한 관점들의 정확도 여부에 따라 추가적으로 토큰을 지급받을 수 있습니다. 관련해서는 추후에 업데이트 될 예정입니다.</li>
            <li>여러 대회 이벤트를 참가해서 추가적으로 토큰을 지급받을 수 있습니다. <a href="{% url 'pybo:free_board' %}">대회 페이지</a>의 공지사항을 참고해주세요!</li>
        </ul>
    </div>

  </div>
</div>
{% endblock %}
{% block script %}
<div class="footer">
    <div class="container text-center">
        <p>제휴제안: <a href="mailto:aiphabtcbusiness@gmail.com">aiphabtcbusiness@gmail.com</a></p>
    </div>
</div>
{% endblock %}

templates/common/ranking.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
{% load static %}
<style>
    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: #f1f1f1;
        text-align: center;
        padding: 10px 0;  /* Adjusted padding to make it slimmer */
        font-size: 0.8rem;  /* You can adjust the font size accordingly */
    }

    .container.my-3 {
        padding-bottom: 50px;  /* Adjusted space to ensure no overlap with the footer */
    }

    .bronze {
        background-color: #CD7F32;  /* Light brown color */
    }

    .silver {
        background-color: #C0C0C0;  /* Light silver color */
    }

    .gold {
        background-color: #FFD700;  /* Light gold color */
    }

    .challenger {
        background-color: #FFA500;  /* Light orange color */
    }

    .grandmaster {
        background-color: #FF4500;  /* Light red color */
    }
</style>

<!-- Sidebar -->
<div class="col-md-2">
    <div class="list-group">
        <a href="{% url 'pybo:board_view' 'perceptive' %}" class="list-group-item list-group-item-action sidebar-item">관점공유 게시판</a>
        <a href="{% url 'pybo:board_view' 'free_board' %}" class="list-group-item list-group-item-action sidebar-item">자유게시판</a>
        <a href="{% url 'pybo:board_view' 'technical_blog' %}" class="list-group-item list-group-item-action sidebar-item">기술 블로그</a>
        <a href="{% url 'pybo:board_view' 'trading_blog' %}" class="list-group-item list-group-item-action sidebar-item">트레이딩 블로그</a>
        <a href="{% url 'pybo:indicator_view' %}" class="list-group-item list-group-item-action sidebar-item">기술 지표 페이지</a>
        <a href="{% url 'pybo:ai_indicator_view' %}" class="list-group-item list-group-item-action sidebar-item">AI 지표 페이지</a>
        <a href="{% url 'pybo:trading_bot_view' %}" class="list-group-item list-group-item-action sidebar-item">투자봇 페이지</a>
        <a href="{% url 'pybo:free_board' %}" class="list-group-item list-group-item-action sidebar-item">대회</a>
    </div>
</div>

<div class="col-md-10">
  <div class="container my-3">
  <h2>User Ranking</h2>
  <h6><a href="{% url 'common:point_policy' %}">포인트 정책</a></h6>
  <div class="card">
    <div class="card-body">
      <table class="table table-hover">
        <thead class="thead-light">
          <tr>
            <th scope="col">Rank</th>
            <th scope="col">User</th>
            <th scope="col">Points</th>
            <th scope="col">Tier</th>
          </tr>
        </thead>
        <tbody>
          {% for profile, rank, tier, icon in profile_list_with_tier %}
            <tr class="{% if tier == 'bronze' %}bronze{% elif tier == 'silver' %}silver{% elif tier == 'gold' %}gold{% elif tier == 'challenger' %}challenger{% elif tier == 'grandmaster' %}grandmaster{% endif %}">
                <td>{{ rank }}</td>
                <td><a href="{% url 'pybo:profile_detail' profile.user.id %}">{{ profile.user.username }}</a></td>
                <td>{{ profile.score }}</td>
                <td>
                    {% if icon %}
                        <img src="{% static icon %}" alt="{{ tier }}" title="{{ tier }}" style="width:30px; height:30px;">
                    {% else %}
                        {{ tier }}
                    {% endif %}
                </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <!-- Pagination -->
      <ul class="pagination justify-content-center">
        {% if profiles.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ profiles.previous_page_number }}">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
          <li class="page-item disabled"><span class="page-link">이전</span></li>
        {% endif %}

        {% for i in profiles.paginator.page_range %}
          {% if profiles.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }}</span></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}

        {% if profiles.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ profiles.next_page_number }}">Next</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ profiles.paginator.num_pages }}">&raquo;</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">다음</span></li>
          <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
        {% endif %}
      </ul>
    </div>
  </div>
  </div>
</div>
{% endblock %}
{% block script %}
<div class="footer">
    <div class="container text-center">
        <p>제휴제안: <a href="mailto:aiphabtcbusiness@gmail.com">aiphabtcbusiness@gmail.com</a></p>
    </div>
</div>
{% endblock %}